services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./deploy/.env.prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fretes}
      POSTGRES_USER: ${POSTGRES_USER:-fretes}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: ghcr.io/brunorimbanojunior/app_frete_web:latest

    environment:
      DJANGO_SETTINGS_MODULE: fretes_web.settings.prod
      DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}  # O Portainer vai substituir
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      CSRF_COOKIE_SECURE: ${CSRF_COOKIE_SECURE:-0}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE:-0}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      GUNICORN_WORKERS: "4"
      GUNICORN_TIMEOUT: "60"
    depends_on:
      - db
    expose:
      - "8000"
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn fretes_web.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60
      "
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8082:80"              # publica no host
    depends_on: [ web ]
    restart: unless-stopped
  
volumes:
  pgdata:
