# Generated by Django 5.2.5 on 2025-08-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FreightTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_ate_50', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_ate_100', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_ate_150', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_ate_200', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_ate_300', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frete_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete por Tonelada')),
                ('frete_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete Mínimo')),
                ('pedagio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pedágio')),
                ('frete_valor_perc', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Frete Valor %')),
                ('fator_peso_cubico', models.DecimalField(decimal_places=2, default=230, max_digits=10, verbose_name='Fator Peso Cúbico')),
                ('carrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tabela', to='fretes.carrier')),
            ],
            options={
                'verbose_name': 'Tabela de Frete',
                'verbose_name_plural': 'Tabelas de Frete',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=60, unique=True)),
                ('picking', models.CharField(blank=True, max_length=120)),
                ('m3', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fretes.carrier')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('altura_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comprimento_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('m3', models.DecimalField(decimal_places=3, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='fretes.pedido')),
            ],
            options={
                'verbose_name': 'Volume do Pedido',
                'verbose_name_plural': 'Volumes do Pedido',
            },
        ),
        migrations.CreateModel(
            name='FreteCalculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calculo', models.DateField(auto_now_add=True)),
                ('numero_pedido', models.CharField(max_length=60)),
                ('numero_nota', models.CharField(blank=True, max_length=60)),
                ('valor_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kg_nota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('m3', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_cubico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_usado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frete_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretes.carrier')),
            ],
            options={
                'verbose_name': 'Frete Calculado',
                'verbose_name_plural': 'Fretes Calculados',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('numero_pedido', 'carrier'), name='uniq_pedido_carrier')],
            },
        ),
    ]
