# Generated by Django 5.2.5 on 2025-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fretecalculado',
            constraint=models.UniqueConstraint(fields=('numero_pedido', 'carrier'), name='uniq_pedido_carrier'),
        ),
    ]
