# Generated by Django 5.2.5 on 2025-08-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidovolume',
            name='m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
