# Generated by hand to add Produto, Cliente e Garantia

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fretes", "0002_alter_pedidovolume_m3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=60, unique=True, verbose_name="Código")),
                ("descricao", models.CharField(max_length=255, verbose_name="Descrição")),
                ("peso_bruto_kg", models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name="Peso bruto (kg)")),
                ("peso_liquido_kg", models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name="Peso líquido (kg)")),
                ("largura_cm", models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Largura (cm)")),
                ("altura_cm", models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Altura (cm)")),
                ("comprimento_cm", models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Comprimento (cm)")),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("cnpj", models.CharField(max_length=20, unique=True, verbose_name="CNPJ")),
                ("endereco", models.CharField(blank=True, max_length=255, verbose_name="Endereço")),
                ("cidade", models.CharField(blank=True, max_length=120, verbose_name="Cidade")),
                ("estado", models.CharField(blank=True, max_length=2, verbose_name="Estado")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("telefone", models.CharField(blank=True, max_length=40, verbose_name="Telefone")),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Garantia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo_peca", models.CharField(max_length=80, verbose_name="Código da peça")),
                ("defeito", models.TextField(verbose_name="Defeito")),
                ("numero_lote", models.CharField(blank=True, max_length=80, verbose_name="Número do lote")),
                ("nota_recebida", models.CharField(max_length=80, verbose_name="Nota recebida")),
                ("valor", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Valor")),
                ("data_recebimento", models.DateField(verbose_name="Data de recebimento")),
                ("nota_retorno", models.CharField(blank=True, max_length=80, verbose_name="Nota de retorno")),
                ("data_retorno", models.DateField(blank=True, null=True, verbose_name="Data de retorno")),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="garantias", to="fretes.cliente")),
            ],
            options={
                "verbose_name": "Garantia",
                "verbose_name_plural": "Garantias",
                "ordering": ["-data_recebimento", "-id"],
            },
        ),
    ]

