# cat 0011_alter_produto_options_alter_cliente_endereco_and_more.py
# Generated by Django 5.2.7 on 2025-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0010_add_despacho_gris'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['codigo'], 'permissions': (('can_import_products', 'Pode importar produtos'), ('can_import_clients', 'Pode importar clientes'), ('can_view_reports', 'Pode acessar relatorios'), ('can_use_calcular', 'Pode usar a ferramenta Calcular')), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='freighttable',
            name='fator_peso_cubico',
            field=models.DecimalField(decimal_places=2, default=230, max_digits=10, verbose_name='Fator Peso Cubico'),
        ),
        migrations.AlterField(
            model_name='freighttable',
            name='frete_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete Minimo'),
        ),
        migrations.AlterField(
            model_name='freighttable',
            name='pedagio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pedagio'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='codigo_peca',
            field=models.CharField(max_length=80, verbose_name='Codigo da peca'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='mao_de_obra',
            field=models.BooleanField(default=False, verbose_name='Com mao de obra'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=80, verbose_name='Numero do lote'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='valor_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor mao de obra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=60, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso_liquido_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Peso liquido (kg)'),
        ),
    ]